services:
  contas-api:
    build:
      context: ./back-end/ContasMensais.API
    container_name: contas-api
    ports:
      - "${API_PORT}:5000"
    volumes:
      - ./back-end/ContasMensais.API/data:/data
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

  contas-web:
    build:
      context: ./front-end/ContasMensais.Web
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: contas-web
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - contas-api
