version: '3.8'

services:
  contas-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contas-api
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data  # Persistência do banco SQLite
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped