name: Build containers do projeto

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Criar arquivo .env
        run: |
          echo "API_PORT=5000" >> .env
          echo "FRONTEND_PORT=3000" >> .env
          echo "ASPNETCORE_ENVIRONMENT=Development" >> .env
          echo "VITE_API_URL=http://localhost:5000" >> .env

      - name: Instalar Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Buildar containers backend e frontend
        run: |
          docker compose --env-file .env -f docker-compose.yaml build
        working-directory: ./
