name: Build containers do projeto

on:
  push:
    branches:
      - main # S칩 executa quando h치 push para a branch principal
  pull_request:
    branches:
      - main
  workflow_dispatch: # Permite rodar manualmente no GitHub

jobs:
  build:
    runs-on: ubuntu-latest # O CI ser치 executado em uma VM Linux da Github

    steps:
      - name: Clonar o reposit칩rio
        uses: actions/checkout@v3

      - name: Criar arquivo .env
        run: |
          echo "API_PORT=5000" >> .env
          echo "FRONTEND_PORT=3000" >> .env
          echo "ASPNETCORE_ENVIRONMENT=Development" >> .env
          echo "VITE_API_URL=http://localhost:5000" >> .env

      - name: Instalar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose-plugin
          docker compose version

      - name: Contruir os containers com Docker Compose
        run: |
          docker compose --env-file .env build